if(NOT DEFINED CC_SOURCE_DIR)
    message(FATAL_ERROR "CC_SOURCE_DIR is required")
endif()

function(assert_file_contains relative_path expected_text)
    set(path "${CC_SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing ${relative_path}")
    endif()

    file(READ "${path}" contents)
    string(FIND "${contents}" "${expected_text}" match_index)
    if(match_index EQUAL -1)
        message(FATAL_ERROR
            "${relative_path} does not contain: ${expected_text}")
    endif()
endfunction()

assert_file_contains("LICENSE" "All rights reserved")
assert_file_contains("LICENSE" "THIRD_PARTY_NOTICES.txt")
assert_file_contains("THIRD_PARTY_NOTICES.txt" "raylib 6.0")
assert_file_contains("THIRD_PARTY_NOTICES.txt" "SQLite — public domain")
assert_file_contains("THIRD_PARTY_NOTICES.txt" "The Predator Clause")
assert_file_contains("web/licenses.html" "Licenses &amp; Credits")
assert_file_contains("web/licenses.html" "LICENSE.txt")
assert_file_contains("web/licenses.html" "THIRD_PARTY_NOTICES.txt")
assert_file_contains("src/client/cc_frontend.inc" "OpenURL(\"licenses.html\")")
assert_file_contains("CMakeLists.txt" "site/licenses.html")
assert_file_contains("CMakeLists.txt" "Resources/THIRD_PARTY_NOTICES.txt")
