#!/usr/bin/env python3
"""Generate the C runtime creature catalog from the asset manifest."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "assets" / "creature_manifest.json"
OUTPUT_PATH = ROOT / "src" / "client" / "cc_creature_catalog.generated.inc"

VARIANT_ENUMS = {
    "goblin_scavenger": "CC_CREATURE_GOBLIN_SCAVENGER",
    "goblin_raider": "CC_CREATURE_GOBLIN_RAIDER",
    "goblin_tribute_bearer": "CC_CREATURE_GOBLIN_TRIBUTE_BEARER",
    "horse": "CC_CREATURE_HORSE",
    "cow": "CC_CREATURE_COW",
    "dragon": "CC_CREATURE_DRAGON",
}
POSE_ENUMS = {
    "idle": "CC_CREATURE_POSE_IDLE",
    "contact_a": "CC_CREATURE_POSE_CONTACT_A",
    "down_a": "CC_CREATURE_POSE_DOWN_A",
    "passing_a": "CC_CREATURE_POSE_PASSING_A",
    "up_a": "CC_CREATURE_POSE_UP_A",
    "contact_b": "CC_CREATURE_POSE_CONTACT_B",
    "down_b": "CC_CREATURE_POSE_DOWN_B",
    "passing_b": "CC_CREATURE_POSE_PASSING_B",
    "up_b": "CC_CREATURE_POSE_UP_B",
    "stalk_a": "CC_CREATURE_POSE_STALK_A",
    "stalk_b": "CC_CREATURE_POSE_STALK_B",
    "threat": "CC_CREATURE_POSE_THREAT",
    "rest": "CC_CREATURE_POSE_REST",
}


def render_catalog(manifest: dict) -> str:
    entries = manifest["archetypes"]
    definitions: dict[str, dict] = {}
    paths: dict[str, list[dict]] = {variant: [] for variant in manifest["variants"]}
    for entry in entries:
        variant = entry["variant"]
        definitions.setdefault(variant, entry)
        paths[variant].append(entry)

    lines = [
        "/* Generated by tools/blender/generate_creature_catalog.py.",
        "   Edit assets/creature_manifest.json through the Blender generator. */",
        "static const CcCreatureDefinition",
        "CC_CREATURE_DEFINITIONS[CC_CREATURE_VARIANT_COUNT] = {",
    ]
    for variant in manifest["variants"]:
        entry = definitions[variant]
        enum = VARIANT_ENUMS[variant]
        quadruped = "true" if entry["runtime_morphology"] == "quadruped" else "false"
        lines.append(
            f'    [{enum}] = {{"{variant}", "{entry["family"]}", '
            f'"{entry["gait_contract"]}", {quadruped}}},'
        )
    lines.extend([
        "};",
        "",
        "static const char *const",
        "CC_CREATURE_ASSET_PATHS[CC_CREATURE_VARIANT_COUNT]",
        "                       [CC_CREATURE_POSE_COUNT] = {",
    ])
    for variant in manifest["variants"]:
        lines.append(f"    [{VARIANT_ENUMS[variant]}] = {{")
        for entry in paths[variant]:
            lines.append(
                f'        [{POSE_ENUMS[entry["pose"]]}] = "{entry["export"]}",'
            )
        lines.append("    },")
    lines.extend(["};", ""])
    return "\n".join(lines)


def generate(manifest_path: Path = MANIFEST_PATH,
             output_path: Path = OUTPUT_PATH) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    output_path.write_text(render_catalog(manifest), encoding="utf-8")
    print(f"runtime catalog: {output_path}")


if __name__ == "__main__":
    generate()
