"""Compile the shared account grammar and inventory every simulation event."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def compile_rules(check=False):
    path = ROOT / 'tools/data/core_account_rules.json'
    data = json.loads(path.read_text())
    enum = (ROOT / 'src/sim/cc_sim.h').read_text().split('typedef enum CcEventKind {')[1].split('}')[0]
    kinds = dict((name, int(value)) for name, value in re.findall(r'CC_EVENT_(\w+)\s*=\s*(\d+)', enum))
    grammar_hash = hashlib.sha256(path.read_bytes()).hexdigest()
    lines = ['/* Generated by tools/compile_core_accounts.py. */',
             '#define CC_CORE_GRAMMAR_SHA256 "' + grammar_hash + '"']
    ids = set()
    for r in data['rules']:
        assert r['kind'] in kinds and r['id'] not in ids
        ids.add(r['id'])
        assert len(r['roles']) <= 8 and len(r['outputs']) == 2
        slots = [int(x) for x in re.findall(r'\{(\d)\}', r['source'])]
        assert sorted(slots) == list(range(len(r['roles'])))
        for template in [*r['outputs'], r['challenge']]:
            assert all(int(x) < len(r['roles']) for x in re.findall(r'\{(\d)\}', template))
        for output in r['outputs']:
            assert all(r['roles'][int(x)] != 'quantity' for x in re.findall(r'\{(\d)\}', output))
            assert set(S for S in re.findall(r'\{(\d)\}', output)) <= set(re.findall(r'\{(\d)\}', r['challenge']))
        roles = [data['roles'].index(x) for x in r['roles']]
        roles += [0] * (8 - len(roles))
        q = lambda x: json.dumps(x, ensure_ascii=True)
        allowed = [q('|' + '|'.join(r.get('allowed', {}).get(str(i), [])) + '|')
                   if str(i) in r.get('allowed', {}) else 'NULL' for i in range(8)]
        positive = sum(1 << i for i in r.get('positive', []))
        left, right = r.get('less_than', [-1, -1])
        if left >= 0: assert r['roles'][left] == r['roles'][right] == 'quantity'
        lines.append('{CC_EVENT_%s, %s, %s, {%s, %s}, %d, {%s}, {%s}, %d, %d, %d},' % (
            r['kind'], q(r['id']), q(r['source']), q(r['outputs'][0]), q(r['outputs'][1]),
            len(r['roles']), ', '.join(map(str, roles)), ', '.join(allowed), positive, left, right))
    coverage = {'version': 1, 'grammar_sha256': hashlib.sha256(path.read_bytes()).hexdigest(),
                'event_count': len(kinds), 'rule_count': len(ids), 'events': []}
    for name, value in kinds.items():
        rules = [r['id'] for r in data['rules'] if r['kind'] == name]
        coverage['events'].append({'kind': name, 'value': value, 'rules': rules,
                                  'status': 'field_rules' if rules else 'legacy_or_uncovered'})
    # Keep the exporter's bounded counters in step with the actual enum.
    last = max(kinds, key=kinds.get)
    assert re.search(r'CC_EVENT_' + last + r'\s*=\s*' + str(kinds[last]) +
                     r'\s*,\s*CC_EVENT_KIND_COUNT\s*$', enum)
    assert '#define KIND_COUNT ((int)CC_EVENT_KIND_COUNT)' in (ROOT / 'tools/gossip_corpus.c').read_text()
    files = {ROOT / 'src/story/cc_core_account_rules.inc': '\n'.join(lines) + '\n',
             ROOT / 'docs/core-account-coverage.json': json.dumps(coverage, indent=2) + '\n'}
    for target, content in files.items():
        if check:
            if not target.exists() or target.read_text() != content:
                raise ValueError(f'Regenerate {target}')
        else:
            target.write_text(content)
    return coverage


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    print(json.dumps(compile_rules(args.check), indent=2))
