#!/usr/bin/env python3
"""Build the C soundtrack catalog from its theme and take metadata."""
import argparse
import json
from pathlib import Path


def render(data):
    cues, takes = data["cues"], data["takes"]
    assert 1 <= len(cues) <= 99
    # The player accepts a 16 KiB catalog, with one 75-byte line per take.
    assert 1 <= len(takes) <= (16384 - len("CROWNLESS_MUSIC 1\n")) // 75
    assert [cue["number"] for cue in cues] == list(range(1, len(cues) + 1))
    lines = ["/* Theme tags for the Crownless soundtrack. */",
             "const CcMusicCue cc_music_cues[CC_MUSIC_CUE_COUNT] = {"]
    for cue in cues:
        assert -1 <= cue["region"] < 6
        for key in ("theme", "secondary"):
            assert cue[key].isidentifier() and cue[key].isascii()
        mood = cue.get("mood", "any")
        assert mood in ("any", "everyday", "shortage", "recovery")
        assert mood == "any" or (cue["place"] and cue["region"] >= 0 and not cue["combat"])
        lines.append("    {%s, %s, CC_MUSIC_%s, CC_MUSIC_%s, %d, %s, CC_MUSIC_MOOD_%s}," % (
            json.dumps(cue["title"]), json.dumps(cue["place"]),
            cue["theme"].upper(), cue["secondary"].upper(), cue["region"],
            "true" if cue["combat"] else "false", mood.upper()))
    lines += ["};", "", "const CcMusicTake cc_music_takes[CC_MUSIC_TAKE_COUNT] = {"]
    seen = set()
    for take in takes:
        key = take["track"], take["variant"]
        assert key not in seen and 1 <= key[0] <= len(cues) and 1 <= key[1] <= 99
        seen.add(key)
        assert take["stem"] == f"{key[0]:02d}-{key[1]:02d}"
        assert 10 <= take["duration"] <= 1800 and 0 < take["weight"] <= 1
        lines.append(f'    {{{key[0]-1}, {key[1]}, {take["duration"]}.0f, {take["weight"]}f}},')
    assert {key[0] for key in seen} == set(range(1, len(cues) + 1))
    return "\n".join(lines + ["};", ""])


def render_counts(data):
    return ("/* Generated by tools/music_catalog.py. */\n"
            "#ifndef CROWNLESS_MUSIC_CATALOG_H\n#define CROWNLESS_MUSIC_CATALOG_H\n\n"
            f'#define CC_MUSIC_CUE_COUNT {len(data["cues"])}\n'
            f'#define CC_MUSIC_TAKE_COUNT {len(data["takes"])}\n\n'
            "#endif\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    source = root / "assets/audio/music/catalog.json"
    data = json.loads(source.read_text())
    outputs = {"cc_music_catalog.inc": render(data), "cc_music_catalog.h": render_counts(data)}
    for name, expected in outputs.items():
        target = root / "src/client" / name
        if args.check:
            if not target.exists() or target.read_text() != expected:
                raise SystemExit("Run python3 tools/music_catalog.py to refresh the C catalog.")
        else:
            target.write_text(expected)


if __name__ == "__main__":
    main()
