#!/usr/bin/env python3
"""Compile the pinned model layout and byte BPE vocabulary for the C runtime."""
import argparse
import hashlib
import json
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[2]
MODEL_SHA = '244a809aba71679efe129495bb981ca8d7fbe0d9012948a5f88731dabcb9c48b'
TOKENIZER_SHA = 'c572de53eb4e739a8ce941ac03d1d5fb6173623af786787cf786b41fd34e9af4'


def compile_tables():
    raw = (ROOT / 'assets/language/core.ccv2').read_bytes()
    tok = (ROOT / 'assets/language/tokenizer.json').read_bytes()
    if hashlib.sha256(raw).hexdigest() != MODEL_SHA or hashlib.sha256(tok).hexdigest() != TOKENIZER_SHA:
        raise ValueError('Model package differs from the reviewed checkpoint')
    size, = struct.unpack_from('<I', raw, 8)
    header = json.loads(raw[12:12 + size])
    lines = ['/* Generated by tools/language/compile_model.py. */',
             '#define CORE_FILE_SIZE %dU' % len(raw),
             '#define CORE_GRAMMAR "%s"' % header['rules_sha256']]
    checksum = 14695981039346656037
    for byte in raw:
        checksum = ((checksum ^ byte) * 1099511628211) & ((1 << 64) - 1)
    lines.append('#define CORE_FILE_HASH UINT64_C(0x%016x)' % checksum)
    lines.append('static const CoreTensorLayout CORE_LAYOUT[] = {')
    for item in header['tensors']:
        rows, cols = (item['shape'] + [0])[:2]
        lines.append('    {%d, %d, %dU, %dU}, /* %s */' % (rows, cols, 12 + size + item['offset'],
                     12 + size + item['scales'] if cols else 0, item['name']))
    lines.append('};')
    lines.append('static const CoreMeaning CORE_MEANINGS[] = {')
    for name, index in sorted(header['meaning_ids'].items()):
        lines.append('    {"%s", %d},' % (name, index))
    lines.append('};')
    tokenizer = json.loads(tok)
    vocab = tokenizer['model']['vocab']
    # ByteLevel uses a bijection from bytes to printable Unicode characters.
    encoded = list(range(33, 127)) + list(range(161, 173)) + list(range(174, 256))
    extra = 0
    byte_chars = {}
    for b in range(256):
        if b in encoded: byte_chars[b] = chr(b)
        else:
            byte_chars[b] = chr(256 + extra)
            extra += 1
    reverse = {c: b for b, c in byte_chars.items()}
    lines.append('static const int CORE_BYTE_IDS[256] = {' + ','.join(str(vocab[byte_chars[b]]) for b in range(256)) + '};')
    lines.append('static const CoreToken CORE_TOKENS[4096] = {')
    for token, index in sorted(vocab.items(), key=lambda item: item[1]):
        data = bytes(reverse[c] for c in token) if index > 8 else b''
        lines.append('    {"%s", %d},' % (''.join('\\x%02x' % b for b in data), len(data)))
    lines.append('};')
    lines.append('static const CoreMerge CORE_MERGES[] = {')
    for a, b in tokenizer['model']['merges']:
        lines.append('    {%d, %d, %d},' % (vocab[a], vocab[b], vocab[a + b]))
    lines.append('};')
    # Unicode categories keep the GPT-2 pre-tokenizer and Python word boundaries.
    ranges = json.loads((ROOT / 'tools/language/unicode_classes.json').read_text())['ranges']
    lines.append('static const CoreClass CORE_CLASSES[] = {')
    for first, last, flags in ranges:
        if flags: lines.append('    {%dU, %dU, %d},' % (first,last,flags))
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true'); args = p.parse_args()
    target = ROOT / 'src/story/cc_core_model_tables.inc'
    generated = compile_tables()
    if args.check:
        if target.read_text() != generated: raise SystemExit('Rebuild the model tables')
    else: target.write_text(generated)

if __name__ == '__main__': main()
